version: 0.2

phases:
  install:
    commands:
      - echo Start package...
      - echo ${bucket}
  build:
    commands:
      - echo Packageing...
      - aws cloudformation package
        --template-file ./iac/template.yaml
        --s3-bucket ${bucket}
        --output-template-file packaged-template.yaml
      - ls -l packaged-template.yaml
      - cat packaged-template.yaml | grep ${bucket}
artifacts:
  files:
    - packaged-template.yaml
